const secret = {
    secret: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYwOTI4MzIyNSwiaWF0IjoxNjA5MjgzMjI1fQ.v1zs3MTiUe4gwmSB11ZFT-iSphVMBCtTrnMDYIXWDmE"
};

export default secret